export const SET_STORE_LIST = 'SET_STORE_LIST';
export const SET_MARKERS = 'SET_MARKERS';

export const FETCH_STORE = 'FETCH_STORE';
export const FETCH_STORE_SUCCEEDED = 'FETCH_STORE_SUCCEEDED';
export const FETCH_STORE_FAILED = 'FETCH_STORE_FAILED';

export const INPUT_USER_INFO = 'INPUT_USER_INFO';
export const INPUT_GUEST_COUNT = 'INPUT_GUEST_COUNT';

export const FETCH_RESERVATION_INFO = 'FETCH_RESERVATION_INFO';
export const FETCH_RESERVATION_INFO_SUCCEEDED = 'FETCH_RESERVATION_INFO_SUCCEEDED';
export const FETCH_RESERVATION_INFO_FAILED = 'FETCH_RESERVATION_INFO_FAILED';