export const SET_STORE_LIST = 'SET_STORE_LIST';

export const FETCH_STORE_DETAIL = 'FETCH_STORE_DETAIL';
export const FETCH_STORE_DETAIL_SUCCEEDED = 'FETCH_STORE_DETAIL_SUCCEEDED';
export const FETCH_STORE_DETAIL_FAILED = 'FETCH_STORE_DETAIL_FAILED';

export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const CLEAR_FIELD_AUTH = 'CLEAR_FIELD_AUTH';

export const INPUT_GUEST_COUNT = 'INPUT_GUEST_COUNT';

export const FETCH_RESERVATION_INFO = 'FETCH_RESERVATION_INFO';
export const FETCH_RESERVATION_INFO_SUCCEEDED = 'FETCH_RESERVATION_INFO_SUCCEEDED';
export const FETCH_RESERVATION_INFO_FAILED = 'FETCH_RESERVATION_INFO_FAILED';

export const FETCH_REVIEW_LIST = 'FETCH_REVIEW_LIST';
export const FETCH_REVIEW_LIST_SUCCEEDED = 'FETCH_REVIEW_LIST_SUCCEEDED';
export const FETCH_REVIEW_LIST_FAILED = 'FETCH_REVIEW_LIST_SUCCEEDED_FAILED';

export const FETCH_REVIEW_DETAIL = 'FETCH_REVIEW_DETAIL';
export const FETCH_REVIEW_DETAIL_SUCCEEDED = 'FETCH_REVIEW_DETAIL_SUCCEEDED';
export const FETCH_REVIEW_DETAIL_FAILED = 'FETCH_REVIEW_DETAIL_FAILED';