export const SET_STORE_LIST = 'SET_STORE_LIST';

export const SET_MARKERS = 'SET_MARKERS';

export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';

export const FETCH_STORE = 'FETCH_STORE';
export const FETCH_STORE_SUCCEEDED = 'FETCH_STORE_SUCCEEDED';
export const FETCH_STORE_FAILED = 'FETCH_STORE_FAILED';

export const TOGGLE_REVIEW = 'TOGGLE_REVIEW';

export const INPUT_USER_INFO = 'INPUT_USER_INFO';